# Logo (Font Awesome Class)
fa_logo: fa-cube

# Header
menu:
  Home: /
  Archives: /archives
  About: /about.html
  Tags: /tags
  Categories: /categories
  Contact: /contact.html

# Default post title
default_post_title: Untitled

# Archive Date Format
archive_date_format: MMM YYYY

# Comments.
comments:
  # Disqus comments
  disqus_shortname:

# Google Analytics Tracking ID
google_analytics:

# Social Accounts
# twitter_url: https://twitter.com/?lang=en
# facebook_url: https://www.facebook.com/
# instagram_url: https://www.instagram.com/
# dribble_url: https://dribbble.com/
github_url: https://github.com/ScarboroughCoral
# googleplus_url: https://plus.google.com/
# behance_url: https://www.behance.net/
# fivehundredpx_url: https://500px.com/
email_url: 3249977074@qq.com
# rss_url: \#

# Footer About Text
footer_about: "不忘初心"

# Footer Copyright Line
footer_copyright: "@Copyright. All right reserved | Design & Hexo <a href=\"http://www.scarboroughcoral.top/\">Scarborough_Coral</a>"

